# Generated by Django 3.0 on 2019-12-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nomorTelepon', models.CharField(max_length=12)),
                ('bidang', models.CharField(max_length=16)),
                ('jadwalPraktek', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kandungan', models.CharField(max_length=50)),
                ('khasiat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nomorTelepon', models.CharField(max_length=12)),
                ('alamat', models.CharField(max_length=50)),
                ('keluhan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('totalHarga', models.IntegerField()),
                ('kumpulanObat', models.CharField(max_length=50)),
            ],
        ),
    ]
