# Generated by Django 3.0 on 2019-12-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kandang',
            old_name='isiKandang',
            new_name='isi_kandang',
        ),
        migrations.RenameField(
            model_name='kandang',
            old_name='luasKandang',
            new_name='luas_kandang',
        ),
        migrations.RenameField(
            model_name='pengunjung',
            old_name='hariBerkunjung',
            new_name='nomor_telepon',
        ),
        migrations.RenameField(
            model_name='penjaga',
            old_name='jadwalJaga',
            new_name='nomor_telepon',
        ),
        migrations.RemoveField(
            model_name='pengunjung',
            name='nomorTelepon',
        ),
        migrations.RemoveField(
            model_name='penjaga',
            name='nomorTelepon',
        ),
        migrations.AddField(
            model_name='pengunjung',
            name='hari_berkunjung',
            field=models.DateTimeField(auto_now=True, verbose_name='Hari Berkunjung'),
        ),
        migrations.AddField(
            model_name='penjaga',
            name='jadwal_jaga',
            field=models.DateTimeField(auto_now=True, verbose_name='Jadwal Jaga'),
        ),
    ]
