# Generated by Django 3.0 on 2019-12-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLengkap', models.CharField(max_length=50)),
                ('noTelepon', models.CharField(max_length=12)),
                ('jabatan', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPelajaran', models.CharField(max_length=12)),
                ('jadwalDimulai', models.CharField(max_length=10)),
                ('jadwalberakhir', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLengkap', models.CharField(max_length=50)),
                ('noTelepon', models.CharField(max_length=12)),
                ('nomorAbsen', models.IntegerField(default=0)),
                ('nilai', models.IntegerField(default=0)),
                ('nilaiRataRata', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLengkap', models.CharField(max_length=50)),
                ('noTelepon', models.CharField(max_length=16)),
                ('mataPelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.MataPelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='LiveCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLiveCode', models.CharField(max_length=20)),
                ('banyakSoal', models.IntegerField(default=0)),
                ('bobotNilai', models.IntegerField(default=0)),
                ('tanggalPelaksanaan', models.CharField(max_length=10)),
                ('mataPelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.MataPelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaChallenge', models.CharField(max_length=20)),
                ('banyakSoal', models.IntegerField(default=0)),
                ('bobotNilai', models.IntegerField(default=0)),
                ('mataPelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.MataPelajaran')),
            ],
        ),
    ]
