# Generated by Django 3.0 on 2019-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='banyakSoal',
            new_name='banyak_soal',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='bobotNilai',
            new_name='bobot_nilai',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='mataPelajaran',
            new_name='mata_pelajaran',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='namaChallenge',
            new_name='nama_challenge',
        ),
        migrations.RenameField(
            model_name='direksi',
            old_name='namaLengkap',
            new_name='nama_lengkap',
        ),
        migrations.RenameField(
            model_name='direksi',
            old_name='noTelepon',
            new_name='no_telepon',
        ),
        migrations.RenameField(
            model_name='livecode',
            old_name='banyakSoal',
            new_name='banyak_soal',
        ),
        migrations.RenameField(
            model_name='livecode',
            old_name='bobotNilai',
            new_name='bobot_nilai',
        ),
        migrations.RenameField(
            model_name='livecode',
            old_name='mataPelajaran',
            new_name='mata_pelajaran',
        ),
        migrations.RenameField(
            model_name='livecode',
            old_name='namaLiveCode',
            new_name='nama_live_code',
        ),
        migrations.RenameField(
            model_name='livecode',
            old_name='tanggalPelaksanaan',
            new_name='tanggal_pelaksanaan',
        ),
        migrations.RenameField(
            model_name='matapelajaran',
            old_name='namaPelajaran',
            new_name='nama_pelajaran',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='namaLengkap',
            new_name='nama_lengkap',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='nilaiRataRata',
            new_name='nilai_rata_rata',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='noTelepon',
            new_name='no_telepon',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='nomorAbsen',
            new_name='nomor_absen',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mataPelajaran',
            new_name='mata_pelajaran',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='namaLengkap',
            new_name='nama_lengkap',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='noTelepon',
            new_name='no_telepon',
        ),
        migrations.RemoveField(
            model_name='matapelajaran',
            name='jadwalDimulai',
        ),
        migrations.RemoveField(
            model_name='matapelajaran',
            name='jadwalberakhir',
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='jadwal_berakhir',
            field=models.DateTimeField(auto_now=True, verbose_name='Jadwal Berakhir'),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='jadwal_dimulai',
            field=models.DateTimeField(auto_now=True, verbose_name='Jadwal Dimulai'),
        ),
    ]
