# Generated by Django 3.0 on 2019-12-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATA', '0002_auto_20191209_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajaran',
            name='jadwal_berakhir',
            field=models.DateTimeField(verbose_name='Jadwal Berakhir'),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='jadwal_dimulai',
            field=models.DateTimeField(verbose_name='Jadwal Dimulai'),
        ),
    ]
